apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage-container
          image: snowballcompany
          imagePullPolicy: Never
          ports:
            - containerPort: 80
